import assert from 'node:assert/strict';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { startApprovalModelFixture } from '../../harness/approval-model.mjs';
import { startGateway,waitForGatewayRpcToken } from '../../harness/gateway.mjs';
import { gatewayRpcUrl,initializeRpc,openRpc } from '../../harness/rpc.mjs';
import { repoRoot,runE2E } from '../../harness/run-context.mjs';
import { materializeWorkspace } from '../../harness/workspace-fixture.mjs';
await runE2E(import.meta.url,{testId:'user-hook-configuration-cas-snapshots-and-ownership',tier:'full-integration',modelPolicy:'model-independent actual JSONC persistence, Shell Hooks and resident conversation snapshots'},async context=>{
 const {path:workspace}=await materializeWorkspace(context,'minimal');
 const fixture=await startApprovalModelFixture(context,{responseSteps:()=>[{delta:{role:'assistant',content:'HOOK_CONFIGURATION_OK'},finishReason:'stop'}]});
 const config=context.pathInState('config');
 const settings={active_provider:'fixture',max_retries:0,providers:{fixture:{api_format:'openai_chat_completions',authentication:{mode:'none'},endpoint:fixture.baseUrl,default_model:'fixture',context_window_tokens:64000,max_output_tokens:1024,output_headroom_tokens:1024,no_proxy:true}}};
 const settingsPath=await context.writeStateJson('config/settings.json',settings);
 await writeFile(settingsPath,'// Owned JSONC comment survives narrow updates\n'+JSON.stringify(settings,null,2));
 await context.writeStateJson('config/trusted-folders.json',{trusted:[workspace],never:[]});
 const hook=command=>[{hooks:[{type:'command',shell:'bash',command,timeout:5}]}];
 const pluginRoot=resolve(workspace,'.kcoder/plugins/owned-hook');await mkdir(pluginRoot,{recursive:true});
 const projectSource=JSON.stringify({hooks:{UserPromptSubmit:hook('printf x >> project-hook-count')}});
 const pluginSource=JSON.stringify({id:'owned-hook',name:'owned-hook',hooks:{UserPromptSubmit:hook('printf x >> plugin-hook-count')}});
 await writeFile(resolve(workspace,'.kcoder/settings.json'),projectSource);
 await writeFile(resolve(pluginRoot,'plugin.json'),pluginSource);
 const binary=process.env.KCODER_E2E_KCODER_BIN||resolve(repoRoot,'target/debug/kcoder');
 const gateway=await startGateway(context,{workspace,kcoderBin:binary,env:{KCODER_CONFIG_DIR:config}});
 const token=await waitForGatewayRpcToken(context,gateway),rpc=await openRpc(gatewayRpcUrl(gateway,'local',token));
 context.addCleanup('close Hook management RPC',()=>rpc.close());
 const initialized=await initializeRpc(rpc,'user-hook-management');
 assert.equal(initialized.capabilities.experimental.hookConfigurationV1,true);
 const original=await rpc.request('hooks/config/read');assert.deepEqual(original.hooks,{});
 const old=(await rpc.request('thread/start',{})).thread.id;
 const save=(configuration,revision)=>rpc.request('hooks/config/update',{hooks:configuration,expectedRevision:revision});
 let saved=await save({UserPromptSubmit:hook('printf A >> user-hook-count')},original.revision);
 assert.equal(await readFile(settingsPath,'utf8').then(text=>text.startsWith('// Owned JSONC')),true);
 await assert.rejects(save({},original.revision),/changed/);
 await assert.rejects(save({Stop:[{source:{kind:'plugin'},hooks:[]}]},saved.revision),/Invalid/);
 assert.equal((await rpc.request('hooks/config/read')).revision,saved.revision);
 const turn=async(id,text)=>{
  const {turn}=await rpc.request('turn/start',{threadId:id,input:[{type:'text',text}]});
  const completed=await rpc.waitFor(message=>message.method==='turn/completed'&&message.params?.threadId===id&&message.params?.turnId===turn.id,30000,'Hook fixture turn');
  assert.equal(completed.params.turn.status,'completed');
 };
 await turn(old,'OLD_BEFORE_USER_HOOK');
 const a=(await rpc.request('thread/start',{})).thread.id;await turn(a,'USER_A');
 saved=await save({UserPromptSubmit:hook('printf B >> user-hook-count')},saved.revision);
 await turn(a,'OLD_A_SNAPSHOT');
 const b=(await rpc.request('thread/start',{})).thread.id;await turn(b,'USER_B');
 await save({},saved.revision);
 const empty=(await rpc.request('thread/start',{})).thread.id;await turn(empty,'NO_USER_HOOK');
 await turn(b,'OLD_B_SNAPSHOT');
 assert.equal(await readFile(resolve(workspace,'user-hook-count'),'utf8'),'AABB');
 for(const name of ['project-hook-count','plugin-hook-count'])assert.equal(await readFile(resolve(workspace,name),'utf8'),'xxxxxx');
 assert.equal(await readFile(resolve(workspace,'.kcoder/settings.json'),'utf8'),projectSource);
 assert.equal(await readFile(resolve(pluginRoot,'plugin.json'),'utf8'),pluginSource);
 const finalSource=await readFile(settingsPath,'utf8');assert.ok(finalSource.includes('// Owned JSONC comment'));
 assert.deepEqual((await rpc.request('hooks/config/read')).hooks,{});
 await context.writeArtifactJson('hook-lifecycle.json',{userHooks:'AABB',projectCalls:6,pluginCalls:6,staleRejected:true,jsoncCommentRetained:true,newConversationOnly:true});
 return {userCrud:true,cas:true,jsonc:true,oldSnapshotRetained:true,pluginAndProjectUnchanged:true};
});
