import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile, rm, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
import { startApprovalModelFixture } from '../../harness/approval-model.mjs';
import { startGateway, waitForGatewayRpcToken } from '../../harness/gateway.mjs';
import { gatewayRpcUrl, initializeRpc, openRpc } from '../../harness/rpc.mjs';
import { repoRoot, runE2E, waitFor } from '../../harness/run-context.mjs';
import { materializeWorkspace } from '../../harness/workspace-fixture.mjs';
await runE2E(import.meta.url,{testId:'plugin-download-failure-preserves-installed-version',tier:'full-integration',modelPolicy:'model-independent real npm registry download, integrity mismatch, runtime interruption and orphan plugin management'},async context=>{
  const {path:workspace}=await materializeWorkspace(context,'minimal',{instanceId:'atomic-plugin'});
  const source=context.pathInState('market');
  const original=resolve(source,'atomic');
  await mkdir(resolve(original,'.claude-plugin'),{recursive:true});
  await mkdir(resolve(source,'.claude-plugin'),{recursive:true});
  await writeFile(resolve(original,'.claude-plugin/plugin.json'),JSON.stringify({name:'atomic',version:'1.0.0',hooks:{UserPromptSubmit:[{hooks:[{type:'command',shell:'bash',command:'printf x >> atomic-hook-count'}]}]}}));
  const packed=context.pathInState('package-root');
  await mkdir(resolve(packed,'package/.claude-plugin'),{recursive:true});
  await writeFile(resolve(packed,'package/package.json'),JSON.stringify({name:'atomic',version:'2.0.0'}));
  await writeFile(resolve(packed,'package/.claude-plugin/plugin.json'),JSON.stringify({name:'atomic',version:'2.0.0'}));
  const tarball=context.pathInState('atomic.tgz');
  const tar=context.spawnOwned('pack-npm-fixture','tar',['-czf',tarball,'-C',packed,'package']);
  await waitFor(()=>tar.exitCode!==null,10000,'fixture archive');assert.equal(tar.exitCode,0);
  const bytes=await readFile(tarball);const integrity='sha512-'+createHash('sha512').update(bytes).digest('base64');
  let mode='healthy';let requests=0;let root;
  const server=createServer((req,res)=>{
    requests++;
    if(mode==='disconnect'){req.socket.destroy();return;}
    if(mode==='hang')return;
    if(req.url.includes('.tgz')){res.writeHead(200,{'content-type':'application/octet-stream'});res.end(bytes);return;}
    res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({name:'atomic','dist-tags':{latest:'2.0.0'},versions:{'2.0.0':{name:'atomic',version:'2.0.0',dist:{tarball:root+'/atomic.tgz',integrity}}}}));
  });
  await new Promise((done,fail)=>{server.once('error',fail);server.listen(0,'127.0.0.1',done);});
  root=`http://127.0.0.1:${server.address().port}`;context.registerPort('npm-registry',server.address().port);
  context.addCleanup('close registry',async()=>{const done=new Promise(resolve=>server.close(resolve));server.closeAllConnections();await done;});
  const manifest=resolve(source,'.claude-plugin/marketplace.json');
  const market=async entry=>writeFile(manifest,JSON.stringify({name:'atomic-market',owner:{name:'Fixture'},plugins:[{name:'atomic',source:entry}]}));
  await market('./atomic');
  const model=await startApprovalModelFixture(context,{textOnly:true,textOnlyResponse:'ATOMIC_OLD_WORKS'});
  await context.writeStateJson('config/settings.json',{active_provider:'fixture',plugins:{installation:{timeout_ms:4000}},providers:{fixture:{api_format:'openai_chat_completions',authentication:{mode:'none'},endpoint:model.baseUrl,default_model:'fixture',context_window_tokens:64000,max_output_tokens:1024,output_headroom_tokens:1024}}});
  await context.writeStateJson('config/credentials.json',{});
  const binary=process.env.KCODER_E2E_KCODER_BIN||resolve(repoRoot,'target/debug/kcoder');
  let gateway=await startGateway(context,{workspace,kcoderBin:binary,env:{KCODER_CONFIG_DIR:context.pathInState('config')}});
  let token=await waitForGatewayRpcToken(context,gateway);
  const connect=async()=>{const rpc=await openRpc(gatewayRpcUrl(gateway,'local',token));context.addCleanup('close atomic RPC',()=>rpc.close());await initializeRpc(rpc,'atomic-install');return rpc;};
  let rpc=await connect();
  await rpc.request('marketplace/add',{source,trustSourceDirectory:true});
  const installed=await rpc.request('plugin/install',{marketplaceName:'atomic-market',pluginName:'atomic'});
  const id=installed.plugin.id;const installedRoot=installed.plugin.root;
  const remains=async()=>{const list=await rpc.request('plugin/list');const plugin=list.plugins.find(p=>p.id===id);assert.equal(plugin.version,'1.0.0');assert.equal(plugin.root,installedRoot);assert.ok(await stat(installedRoot));};
  await market({source:'npm',package:'atomic',version:'2.0.0',registry:root,integrity:'sha512-'+Buffer.alloc(64).toString('base64')});
  await assert.rejects(rpc.request('plugin/install',{marketplaceName:'atomic-market',pluginName:'atomic'}),/integrity/i);await remains();
  mode='disconnect';
  await assert.rejects(rpc.request('plugin/install',{marketplaceName:'atomic-market',pluginName:'atomic'}));await remains();
  mode='hang';const cancelBefore=requests;
  const cancelledInstall=rpc.request('plugin/install',{marketplaceName:'atomic-market',pluginName:'atomic',installAttemptId:'cancel-download'}).then(()=>({succeeded:true}),error=>({error}));
  await waitFor(()=>requests>cancelBefore,15000,'download before explicit cancellation');
  assert.equal((await rpc.request('plugin/install/cancel',{installAttemptId:'cancel-download'})).cancellationRequested,true);
  const cancelled=await cancelledInstall;assert.ok(cancelled.error);assert.match(cancelled.error.message,/cancelled/i);
  await remains();
  assert.equal((await rpc.request('plugin/install/cancel',{installAttemptId:'cancel-download'})).cancellationRequested,false);
  mode='hang';const before=requests;
  const pending=rpc.request('plugin/install',{marketplaceName:'atomic-market',pluginName:'atomic'}).then(()=>{throw new Error('interrupted installation published');},()=>true);
  await waitFor(()=>requests>before,15000,'active npm download');
  rpc.close();
  await context.stopOwned('gateway');
  await pending;
  gateway=await startGateway(context,{label:'gateway-restored',workspace,kcoderBin:binary,env:{KCODER_CONFIG_DIR:context.pathInState('config')}});
  token=await waitForGatewayRpcToken(context,gateway);
  rpc=await connect();await remains();
  await rm(source,{recursive:true});await remains();
  await rpc.request('plugin/disable',{pluginId:id});await rpc.request('plugin/enable',{pluginId:id});
  const {thread}=await rpc.request('thread/start',{});
  const {turn}=await rpc.request('turn/start',{threadId:thread.id,input:[{type:'text',text:'Use preserved plugin'}]});
  const done=await rpc.waitFor(m=>m.method==='turn/completed'&&m.params?.turnId===turn.id,30000,'old plugin works');assert.equal(done.params.turn.status,'completed');
  assert.equal(await readFile(resolve(workspace,'atomic-hook-count'),'utf8'),'x');
  await rpc.request('thread/delete',{threadId:thread.id});await rpc.request('plugin/uninstall',{pluginId:id});
  assert.ok(!(await rpc.request('plugin/list')).plugins.some(p=>p.id===id));
  return {explicitCancellationAtomic:true,integrityFailureAtomic:true,disconnectAtomic:true,interruptedDownloadAtomic:true,orphanManageable:true,oldHookCalls:1};
});
