import { colors, radius, spacing } from "@/theme";
import { Platform, StyleSheet } from "react-native";

export const markdownStyles = {
  body: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 23,
    ...(Platform.OS === "web"
      ? { overflowWrap: "anywhere" as const, wordBreak: "break-word" as const }
      : {}),
  },
  paragraph: { marginTop: 0, marginBottom: 10 },
  code_inline: {
    color: colors.text,
    backgroundColor: colors.surfaceHover,
    fontFamily: "monospace",
    fontSize: 13,
  },
  fence: {
    color: colors.text,
    backgroundColor: colors.background,
    borderColor: colors.border,
    padding: 12,
  },
  code_block: {
    color: colors.text,
    backgroundColor: colors.background,
    borderColor: colors.border,
    padding: 12,
  },
  bullet_list: { marginBottom: 10 },
  strong: { fontWeight: "700" as const },
  link: { color: colors.blue },
  fileCodeLink: {
    color: colors.accentBright,
    textDecorationLine: "underline" as const,
  },
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  center: { alignItems: "center", justifyContent: "center" },
  loadingWorkspaceLabel: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: spacing.md,
  },
  backTextButton: { padding: spacing.lg },
  backText: { color: colors.blue, fontWeight: "600" },
  header: {
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    paddingHorizontal: spacing.xs,
  },
  headerButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
  },
  headerCopy: { flex: 1, minWidth: 0, alignItems: "center" },
  headerTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "700",
    maxWidth: "92%",
  },
  statusRow: {
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 3,
  },
  statusDot: { width: 6, height: 6, borderRadius: 6 },
  online: { backgroundColor: colors.green },
  offline: { backgroundColor: colors.red },
  statusText: {
    color: colors.textDim,
    fontSize: 10,
    maxWidth: 230,
    flexShrink: 1,
  },
  retainedPanel: { flex: 1 },
  hiddenPanel: { display: "none" },
  panel: { flex: 1 },
  messageListStage: { flex: 1, position: "relative" },
  messages: { flex: 1 },
  messageContent: {
    paddingVertical: spacing.lg,
    paddingBottom: spacing.xxl,
    flexGrow: 1,
  },
  historyButton: {
    minHeight: 44,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
  },
  historyButtonText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  jumpToLatest: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.lg,
    zIndex: 4,
    minHeight: 44,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderAccent,
    backgroundColor: colors.surfaceRaised,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  jumpToLatestText: { color: colors.text, fontSize: 12, fontWeight: "700" },
  messageRow: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    alignItems: "flex-start",
  },
  userMessageRow: { alignItems: "flex-end" },
  messageBubble: { maxWidth: "94%", borderRadius: radius.lg },
  userBubble: {
    backgroundColor: colors.surfaceRaised,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomRightRadius: 5,
  },
  assistantBubble: { width: "100%" },
  userText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  assistantLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: spacing.sm,
  },
  assistantLabelText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  cancelledMessage: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  thinkingBox: {
    borderLeftWidth: 2,
    borderLeftColor: colors.border,
    paddingLeft: spacing.sm,
    marginBottom: spacing.md,
  },
  disclosureHeader: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  thinkingTitle: { color: colors.textMuted, fontSize: 11, fontWeight: "700" },
  thinkingPreview: {
    color: colors.textDim,
    fontSize: 12,
    lineHeight: 18,
    paddingLeft: 20,
  },
  thinkingText: {
    color: colors.textDim,
    fontSize: 12,
    lineHeight: 18,
    paddingLeft: 20,
  },
  tool: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    marginTop: spacing.sm,
    overflow: "hidden",
  },
  toolHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    padding: spacing.md,
  },
  toolCopy: { flex: 1 },
  toolName: { color: colors.text, fontSize: 13, fontWeight: "600" },
  toolOutput: {
    color: colors.textDim,
    fontFamily: "monospace",
    fontSize: 11,
    marginTop: 5,
  },
  toolStatus: { color: colors.green, fontSize: 10, fontWeight: "700" },
  toolRunning: { color: colors.yellow },
  toolFailed: { color: colors.red },
  toolDetails: {
    gap: spacing.md,
    padding: spacing.md,
    paddingTop: 0,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  toolDetailLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
    marginBottom: 5,
    marginTop: spacing.sm,
  },
  toolDetailCode: {
    color: colors.text,
    fontFamily: "monospace",
    fontSize: 11,
    lineHeight: 17,
  },
  timelineCard: {
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  timelineHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    padding: spacing.md,
  },
  timelineTitle: { color: colors.text, fontSize: 13, fontWeight: "700" },
  timelineDetail: {
    color: colors.textDim,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  interactionAnswer: {
    color: colors.green,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 6,
  },
  todoList: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
  },
  todoRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  todoDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.textDim,
    alignItems: "center",
    justifyContent: "center",
  },
  todoDotDone: { borderColor: colors.green, backgroundColor: colors.green },
  todoText: { flex: 1, color: colors.text, fontSize: 12, lineHeight: 18 },
  todoTextDone: { color: colors.textDim, textDecorationLine: "line-through" },
  activityCard: {
    minHeight: 48,
    marginTop: spacing.sm,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  activityHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  activityDot: { width: 8, height: 8, borderRadius: 4 },
  activityLabel: { color: colors.text, fontSize: 12, fontWeight: "600" },
  activityStatus: { fontSize: 10, fontWeight: "700" },
  activitySteerButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
    backgroundColor: colors.background,
  },
  activitySteerButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
  },
  activitySteerForm: {
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  activitySteerInput: {
    minHeight: 88,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    borderRadius: radius.md,
    color: colors.text,
    backgroundColor: colors.background,
    padding: spacing.md,
    textAlignVertical: "top",
  },
  activitySteerError: { color: colors.red, fontSize: 12 },
  activitySteerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.sm,
  },
  activitySteerCancel: {
    minWidth: 72,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
    backgroundColor: colors.background,
  },
  activitySteerCancelText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  activitySteerSubmit: {
    minWidth: 88,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    borderRadius: radius.md,
    backgroundColor: colors.text,
  },
  activitySteerSubmitText: {
    color: colors.background,
    fontSize: 12,
    fontWeight: "700",
  },
  disabledButton: { opacity: 0.4 },
  changesCard: {
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: 5,
  },
  changeCardPressed: { backgroundColor: colors.surfaceHover },
  changesHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  changesHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  changesTitle: { color: colors.text, fontSize: 13, fontWeight: "700" },
  changeSummary: { flexDirection: "row", alignItems: "center", gap: 5 },
  changeAdditions: {
    color: colors.green,
    fontFamily: "monospace",
    fontSize: 11,
  },
  changeDeletions: { color: colors.red, fontFamily: "monospace", fontSize: 11 },
  changedFile: {
    color: colors.textMuted,
    fontFamily: "monospace",
    fontSize: 10,
  },
  reviewHint: { color: colors.textDim, fontSize: 10, marginTop: spacing.sm },
  thinkingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  thinkingLabel: { color: colors.textMuted, fontSize: 13 },
  errorBanner: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.md,
    backgroundColor: "rgba(251,113,133,0.12)",
    borderRadius: radius.md,
  },
  errorText: { color: colors.red, fontSize: 13, lineHeight: 19 },
  errorDetailsButton: {
    minHeight: 44,
    alignSelf: "flex-start",
    justifyContent: "center",
    marginTop: spacing.xs,
  },
  errorDetailsText: {
    color: colors.red,
    fontSize: 12,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  connectionBanner: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: "rgba(250,204,21,0.1)",
  },
  connectionBannerText: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  archivedCalloutWrap: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  archivedCallout: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
  },
  archivedCalloutText: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  archivedCalloutButton: {
    minWidth: 58,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.md,
    backgroundColor: colors.surfaceRaised,
  },
  archivedCalloutButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  composerWrap: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  slashMenu: {
    maxHeight: 228,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceRaised,
  },
  slashMenuContent: { flexGrow: 0 },
  slashMenuRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  slashMenuRowPressed: { backgroundColor: colors.surfaceHover },
  slashMenuName: {
    width: 78,
    color: colors.text,
    fontFamily: "monospace",
    fontSize: 12,
    fontWeight: "700",
  },
  slashMenuDescription: {
    minWidth: 0,
    flex: 1,
    color: colors.textMuted,
    fontSize: 11,
  },
  composer: {
    minHeight: 52,
    maxHeight: 150,
    flexDirection: "row",
    alignItems: "flex-end",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    backgroundColor: colors.surface,
    paddingLeft: spacing.md,
    paddingRight: 6,
    paddingVertical: 6,
  },
  attachButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -10,
  },
  composerInput: {
    flex: 1,
    minHeight: 38,
    maxHeight: 130,
    color: colors.text,
    fontSize: 15,
    lineHeight: 21,
    paddingTop: 8,
    paddingBottom: 8,
    textAlignVertical: "top",
  },
  stopButton: {
    width: 44,
    height: 44,
    marginRight: 4,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    backgroundColor: colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  sendDisabled: { opacity: 0.35 },
  composerMeta: {
    height: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.xs,
  },
  modelSelectorMeta: {
    minWidth: 44,
    minHeight: 28,
    maxWidth: "78%",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: spacing.xs,
  },
  model: { flexShrink: 1, color: colors.textDim, fontSize: 10 },
  connection: { color: colors.textDim, fontSize: 10 },
  queueList: { gap: spacing.sm, paddingBottom: spacing.sm },
  queueChip: {
    width: 250,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingLeft: spacing.sm,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceRaised,
  },
  queueIndex: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
  },
  queueIndexText: { color: colors.textMuted, fontSize: 10, fontWeight: "700" },
  queueCopy: { flex: 1, minWidth: 0, paddingVertical: 7 },
  queueText: { color: colors.text, fontSize: 11, fontWeight: "600" },
  queueMeta: { marginTop: 3, color: colors.textDim, fontSize: 9 },
  queueRemove: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  attachmentList: { gap: spacing.sm, paddingBottom: spacing.sm },
  stagedAttachmentItem: { width: 220, gap: 4 },
  attachmentChip: {
    width: "100%",
    height: 34,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  attachmentChipOpen: {
    minWidth: 0,
    flex: 1,
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingLeft: spacing.sm,
  },
  attachmentChipRemove: {
    width: 34,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  attachmentName: {
    minWidth: 0,
    flexShrink: 1,
    color: colors.text,
    fontSize: 11,
  },
  stagedAttachmentError: { color: colors.red, fontSize: 10, lineHeight: 14 },
  attachmentError: {
    color: colors.red,
    fontSize: 11,
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.sm,
  },
  composerNotice: {
    color: colors.green,
    fontSize: 11,
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.sm,
  },
  attachmentSheetError: {
    color: colors.red,
    fontSize: 12,
    lineHeight: 18,
    padding: spacing.sm,
    borderRadius: radius.sm,
    backgroundColor: "rgba(198,79,67,0.12)",
  },
  messageAttachment: {
    minHeight: 52,
    marginTop: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  messageAttachmentCopy: { flex: 1, minWidth: 0 },
  messageAttachmentText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
  },
  messageAttachmentMeta: { color: colors.textDim, fontSize: 10, marginTop: 3 },
  attachmentLightbox: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.92)",
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.lg,
  },
  attachmentLightboxImage: {
    width: "100%",
    height: "100%",
    maxWidth: 960,
    maxHeight: 720,
  },
  attachmentLightboxActions: {
    position: "absolute",
    flexDirection: "row",
    gap: spacing.sm,
  },
  lightboxError: {
    maxWidth: 320,
    color: "#fff",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    padding: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: "rgba(40,40,40,0.9)",
  },
  lightboxButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(30,30,30,0.85)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  modelPickerSheet: {
    maxHeight: "78%",
    marginTop: "auto",
    padding: spacing.lg,
    gap: spacing.md,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    backgroundColor: colors.surfaceRaised,
  },
  modelPickerSubtitle: { marginTop: 3, color: colors.textDim, fontSize: 11 },
  modelPickerLoading: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  modelPickerList: { flexGrow: 0, maxHeight: 330 },
  modelPickerContent: { gap: spacing.sm },
  modelPickerOption: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.background,
  },
  modelPickerSelected: {
    borderColor: colors.green,
    backgroundColor: "rgba(33,132,84,0.08)",
  },
  modelPickerCopy: { flex: 1 },
  modelPickerName: { color: colors.text, fontSize: 13, fontWeight: "700" },
  modelPickerProvider: { marginTop: 4, color: colors.textDim, fontSize: 10 },
  modelPickerCheck: { color: colors.green, fontSize: 18, fontWeight: "700" },
  modelPickerEmpty: {
    color: colors.textMuted,
    fontSize: 12,
    textAlign: "center",
    padding: spacing.lg,
  },
  modelPickerSection: {
    marginBottom: spacing.sm,
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  modelEffortList: { gap: spacing.sm },
  modelEffort: {
    minWidth: 72,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.background,
  },
  modelEffortSelected: {
    borderColor: colors.green,
    backgroundColor: "rgba(33,132,84,0.08)",
  },
  modelEffortText: { color: colors.textMuted, fontSize: 12, fontWeight: "600" },
  modelEffortTextSelected: { color: colors.green },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  attachmentSheet: {
    marginTop: "auto",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  attachmentSheetHeader: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: spacing.sm,
  },
  attachmentSheetTitle: { color: colors.text, fontSize: 18, fontWeight: "700" },
  modalClose: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    margin: -10,
  },
  attachmentAction: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  attachmentActionTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  attachmentActionBody: { color: colors.textMuted, fontSize: 11, marginTop: 3 },
  attachmentProgress: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  taskMenu: {
    marginTop: "auto",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    gap: spacing.sm,
  },
  taskTitleInput: {
    height: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.text,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surface,
  },
  taskMenuRow: {
    minHeight: 46,
    justifyContent: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  taskMenuText: { color: colors.text, fontSize: 14 },
  taskMenuDanger: { color: colors.red, fontSize: 14 },
  taskMenuMessage: {
    color: colors.textMuted,
    fontSize: 12,
    textAlign: "center",
  },
  panelMenu: {
    marginTop: "auto",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    gap: spacing.sm,
  },
  panelMenuRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  panelMenuTitle: { color: colors.text, fontSize: 14, fontWeight: "700" },
  panelMenuBody: { color: colors.textMuted, fontSize: 11, marginTop: 3 },
  panelLimitText: {
    color: colors.yellow,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: spacing.xs,
  },
});
