[package]
name = "kcoder_api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
kcoder_config = { path = "../kcoder_config" }
kcoder_types = { path = "../kcoder_types" }
async-stream = { workspace = true }
eventsource-stream = "0.2"
reqwest = { workspace = true }
reqwest_genai = { package = "reqwest", version = "0.13", default-features = false, features = [
    "rustls",
    "gzip",
    "socks",
    "system-proxy",
] }
reqwest-eventsource = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
genai = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
