import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { startOwnedAiVerify } from '../../harness/ai-verify-client.mjs';
import { assertRendererBuildFresh } from '../../harness/renderer-build.mjs';
import { appRoot, repoRoot, runE2E, waitFor } from '../../harness/run-context.mjs';
await assertRendererBuildFresh();
if(!process.env.KCODER_E2E_TAURI_BIN)throw new Error('Explicit Tauri binary required');
await runE2E(import.meta.url,{testId:'tauri-file-crlf-encoding-conflict-and-truncation',tier:'manual-live',modelPolicy:'model-independent native file tree, actual CodeMirror edits and owned disk bytes'},async context=>{
  const client=await startOwnedAiVerify(context,{tauriBin:process.env.KCODER_E2E_TAURI_BIN,kcoderBin:process.env.KCODER_E2E_KCODER_BIN||resolve(repoRoot,'target/debug/kcoder'),rendererRoot:resolve(appRoot,'renderer/dist')});
  const workspace=resolve(dirname(dirname(client.settingsPath)),'workspaces/tauri-verification');
  const source='\uFEFF'+Array.from({length:999},(_,i)=>`第${i}行 owned-file-fixture`).join('\r\n')+'\r\nLAST_NATIVE_LINE\r\n\r\n';
  const file=resolve(workspace,'native-long.txt');await writeFile(file,source);
  await writeFile(resolve(workspace,'native-large.txt'),'oversized-line\n'.repeat(30000));
  const cmd=(action,id,args={})=>client.command(action,{selector:`[data-testid="${id}"]`,...args});
  const item=name=>`[data-testid="workspace-file-tree-pierre"] >>> button[data-item-path$="${name}"]`;
  const content='[data-testid="workspace-file-editor"] .cm-content';
  try{
    await client.command('navigate',{value:'/'});await cmd('waitFor','desktop-sidebar',{timeoutMs:15000});
    await cmd('click','toggle-right-workspace-panel-button');await cmd('waitFor','right-workspace-file-option',{timeoutMs:15000});await cmd('click','right-workspace-file-option');
    await client.command('waitFor',{selector:item('native-long.txt'),timeoutMs:20000});await client.command('click',{selector:item('native-long.txt')});
    await cmd('waitFor','workspace-file-edit-button',{timeoutMs:15000});await cmd('click','workspace-file-edit-button');
    await client.command('waitFor',{selector:content,timeoutMs:15000});
    const changed=source.replace('LAST_NATIVE_LINE','');
    await client.command('press',{selector:content,key:'Control+End'});
    await waitFor(async()=> (await client.command('getText',{selector:content})).includes('LAST_NATIVE_LINE'),10000,'native end line');
    await client.command('selectText',{selector:content,value:'LAST_NATIVE_LINE'});
    await client.command('press',{selector:content,key:'Backspace'});
    await waitFor(async()=> !(await client.command('getText',{selector:content})).includes('LAST_NATIVE_LINE'),10000,'native keyboard deletion');
    const [line]=JSON.parse(await client.command('getElementMetrics',{selector:content+' .cm-line:last-child'}));
    const [editor]=JSON.parse(await cmd('getElementMetrics','workspace-file-editor'));
    assert.ok(line.bottom<=editor.bottom+1,'native editor final empty line is reachable');
    await client.capture('native-file-last-line.png');
    await cmd('waitFor','workspace-file-save-button',{enabled:true});await cmd('click','workspace-file-save-button');
    await waitFor(async()=>Number(await cmd('getElementCount','workspace-file-editor'))===0,15000,'native file save');
    const actual = await readFile(file, 'utf8');
    await context.writeArtifactJson('encoding-difference.json', { expectedBytes: Buffer.byteLength(changed), actualBytes: Buffer.byteLength(actual), expectedCRLF: (changed.match(/\r\n/g)||[]).length, actualCRLF: (actual.match(/\r\n/g)||[]).length, actualLF: (actual.match(/\n/g)||[]).length, bom: actual.charCodeAt(0) === 0xFEFF, prefix: actual.slice(0,100), suffix: actual.slice(-120) });
    assert.equal(actual, changed, 'native save preserves exact BOM/Unicode/CRLF/trailing empty lines');
    await cmd('click','workspace-file-edit-button');await client.command('fill',{selector:content,value:'LOCAL_DRAFT'});
    await writeFile(file,'EXTERNAL_DISK\r\n');await cmd('click','workspace-file-save-button');
    await cmd('waitFor','workspace-file-save-error',{timeoutMs:15000});assert.match(await cmd('getText','workspace-file-save-error'),/changed on disk|磁盘.*变更|冲突/i);
    assert.equal(await readFile(file,'utf8'),'EXTERNAL_DISK\r\n');await cmd('click','workspace-file-conflict-reload-button');
    await cmd('waitFor','workspace-file-edit-button',{timeoutMs:15000});
    await client.command('click',{selector:item('native-large.txt')});
    await waitFor(async()=> (await client.command('getText',{selector:'body'})).includes('仅显示前 256 KiB'),15000,'native truncated preview');
    assert.equal(Number(await cmd('getElementCount','workspace-file-edit-button')),0);
    await client.capture('native-file-truncated.png');
  }catch(error){client.markFailed();await client.capture('failure.png').catch(()=>{});throw error;}
});
