import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { expect } from '../../../renderer/node_modules/@playwright/test/index.mjs';
import { startGateway } from '../../harness/gateway.mjs';
import { startChromium } from '../../harness/chromium.mjs';
import { usageChartFixture } from '../../harness/usage-chart-fixture.mjs';
import { assertRendererBuildFresh } from '../../harness/renderer-build.mjs';
import { repoRoot, runE2E } from '../../harness/run-context.mjs';
import { materializeWorkspace } from '../../harness/workspace-fixture.mjs';
await assertRendererBuildFresh();
await runE2E(import.meta.url,{testId:'usage-calendar-trend-keyboard-and-corrupt-data',tier:'full-integration',modelPolicy:'model-independent real durable usage ledger RPC and Chromium rendering; fixture counters are synthetic'},async context=>{
  const fixture=usageChartFixture();
  const {path:workspace}=await materializeWorkspace(context,'minimal',{instanceId:'usage-charts'});
  await context.writeStateJson('config/settings.json',{providers:{}});
  const ledger=await context.writeStateJson('config/usage/usage.json',fixture.history);
  const gateway=await startGateway(context,{workspace,kcoderBin:process.env.KCODER_E2E_KCODER_BIN||resolve(repoRoot,'target/debug/kcoder'),env:{KCODER_CONFIG_DIR:context.pathInState('config')}});
  const browser=await startChromium(context);const page=await browser.newPage({viewport:{width:1000,height:850}});
  try{
    await page.goto(gateway.baseUrl+'/settings/usage',{waitUntil:'domcontentloaded'});
    await expect(page.getByTestId('usage-totalTokens')).toHaveText('150',{timeout:30000});
    const heat=page.getByTestId('usage-heatmap');const detail=page.getByTestId('usage-day-detail');
    const initial=await page.getByTestId('usage-heatmap-viewport').evaluate(e=>{const last=e.querySelector('button:last-child').getBoundingClientRect();const view=e.getBoundingClientRect();return{right:last.right,limit:view.right};});
    assert.ok(initial.right+3<=initial.limit,'new charts reveal the latest date by default');
    const trendInitial=await page.getByTestId('usage-trend').evaluate(e=>({right:[...e.querySelectorAll('button[data-date]')].at(-1).getBoundingClientRect().right,limit:e.getBoundingClientRect().right,scroll:e.scrollLeft}));
    assert.ok(trendInitial.scroll>0,'narrow trend initially reveals the latest bars');
    assert.ok(await heat.locator('[data-date]').count()>=176);
    assert.ok(new Set(await heat.locator('[data-date]').evaluateAll(nodes=>nodes.map(n=>n.dataset.date.slice(0,7)))).size>=6);
    await heat.locator(`[data-date="${fixture.missing}"]`).click();await expect(detail).toContainText('不代表没有消耗');
    await heat.locator(`[data-date="${fixture.zero}"]`).click();await expect(detail).toContainText('没有已记录的请求');
    const last=heat.locator(`[data-date="${fixture.today}"]`);await last.focus();await page.keyboard.press('Home');
    await expect(heat.locator('[data-date]').first()).toBeFocused();await page.keyboard.press('End');await expect(last).toBeFocused();
    await expect(detail).toContainText(fixture.today);await expect(detail).toContainText('alpha · 100');
    const bounds=await page.getByTestId('usage-heatmap-viewport').evaluate(element=>{const last=element.querySelector('[data-testid="usage-heatmap"] button:last-child');const view=element.getBoundingClientRect();const cell=last.getBoundingClientRect();return{viewRight:view.right,cellRight:cell.right,viewBottom:view.bottom,cellBottom:cell.bottom};});
    assert.ok(bounds.cellRight+3<=bounds.viewRight,'last column reserves visible focus ring space');
    await page.keyboard.press('Escape');await expect(detail).toContainText('每日详情');
    const legend=page.getByTestId('usage-trend-legend');await legend.getByRole('button',{name:'alpha',exact:true}).click();
    await expect(page.getByTestId('usage-trend').locator('[data-series="alpha"]')).toHaveCount(0);
    await legend.getByRole('button',{name:'alpha',exact:true}).click();
    await page.getByTestId('usage-trend').locator(`[data-date="${fixture.yesterday}"]`).hover();await expect(detail).toContainText('beta · 50');
    await page.getByTestId('usage-range-7').click();await expect(page.getByTestId('usage-trend').locator('button[data-date]')).toHaveCount(7);
    await page.getByTestId('usage-range-30').click();await expect(page.getByTestId('usage-trend').locator('button[data-date]')).toHaveCount(30);
    await page.getByTestId('usage-charts').screenshot({path:context.pathInArtifacts('usage-chart-controls.png')});
    await writeFile(ledger,'{invalid');await page.getByTestId('usage-refresh').click();
    await expect(page.locator('[role="alert"]')).toBeVisible();await expect(page.getByTestId('usage-charts')).toHaveCount(0);
    assert.ok(!/[A-Za-z]{4}/.test(await page.locator('[role="alert"]').innerText()),'Chinese error must be localized, not a backend diagnostic');
    await page.screenshot({path:context.pathInArtifacts('usage-load-error.png')});
    await writeFile(ledger,JSON.stringify(fixture.history));await page.getByTestId('usage-refresh').click();await expect(page.getByTestId('usage-totalTokens')).toHaveText('150');
    return{calendarDays:await heat.locator('[data-date]').count(),zeroDistinctFromMissing:true,keyboard:true,legendAndRange:true,errorDistinctFromZero:true};
  }catch(error){await page.screenshot({path:context.pathInArtifacts('failure.png')}).catch(()=>{});throw error;}
});
