use super::*;

enum TerminalEventCommand {
    Pause(oneshot::Sender<()>),
    Resume,
}

const TERMINAL_PROBE_RESPONSE_FILTER_WINDOW: Duration = Duration::from_secs(300);
const TERMINAL_PROBE_RESPONSE_MAX_CHARS: usize = 96;

struct TerminalProbeResponseFilter {
    active: bool,
    expires_at: Instant,
    pending_events: Vec<CEvent>,
    pending_text: String,
    discarded_responses: u8,
}

#[cfg(any(windows, test))]
const WINDOWS_CONSOLE_PASTE_MIN_CHARS: usize = 32;

#[cfg(any(windows, test))]
fn windows_console_paste_char(event: &CEvent) -> Option<char> {
    let CEvent::Key(key) = event else {
        return None;
    };
    if !matches!(key.kind, KeyEventKind::Press | KeyEventKind::Repeat) {
        return None;
    }
    match key.code {
        KeyCode::Char(ch) if key.modifiers.is_empty() && !ch.is_ascii_control() => Some(ch),
        KeyCode::Enter if key.modifiers.is_empty() || key.modifiers == KeyModifiers::CONTROL => {
            Some('\n')
        }
        KeyCode::Char('\n' | '\r') if key.modifiers.is_empty() => Some('\n'),
        _ => None,
    }
}

#[cfg(any(windows, test))]
fn coalesce_windows_console_paste_events(events: Vec<CEvent>) -> Vec<CEvent> {
    let mut output = Vec::with_capacity(events.len());
    let mut index = 0usize;
    while index < events.len() {
        if windows_console_paste_char(&events[index]).is_none() {
            output.push(events[index].clone());
            index += 1;
            continue;
        }

        let start = index;
        let mut text = String::new();
        let mut has_newline = false;
        let mut previous_was_plain_enter = false;
        let mut trailing_submit = None;
        let mut content_end = start;
        while index < events.len() {
            if let Some(ch) = windows_console_paste_char(&events[index]) {
                let is_plain_enter = matches!(
                    &events[index],
                    CEvent::Key(KeyEvent {
                        code: KeyCode::Enter,
                        modifiers: KeyModifiers::NONE,
                        ..
                    })
                );
                let has_later_character = events[index + 1..]
                    .iter()
                    .take_while(|event| {
                        windows_console_paste_char(event).is_some()
                            || matches!(
                                event,
                                CEvent::Key(KeyEvent {
                                    kind: KeyEventKind::Release,
                                    ..
                                })
                            )
                    })
                    .any(|event| windows_console_paste_char(event).is_some());
                // A physical Enter following an IME commit is a submit action,
                // not part of the committed text. ConPTY's pasted CRLF has a
                // following Ctrl+Enter record and therefore stays in the paste.
                if is_plain_enter && !has_later_character {
                    trailing_submit = Some(events[index].clone());
                    index += 1;
                    while index < events.len()
                        && matches!(
                            &events[index],
                            CEvent::Key(KeyEvent {
                                kind: KeyEventKind::Release,
                                ..
                            })
                        )
                    {
                        index += 1;
                    }
                    break;
                }
                let is_ctrl_enter = matches!(
                    &events[index],
                    CEvent::Key(KeyEvent {
                        code: KeyCode::Enter,
                        modifiers: KeyModifiers::CONTROL,
                        ..
                    })
                );
                has_newline |= ch == '\n';
                // A CRLF written through ConPTY arrives as plain Enter (CR)
                // followed by Ctrl+Enter (LF). Preserve it as one newline.
                if !(is_ctrl_enter && previous_was_plain_enter) {
                    text.push(ch);
                }
                previous_was_plain_enter = is_plain_enter;
                index += 1;
                content_end = index;
            } else if matches!(
                &events[index],
                CEvent::Key(KeyEvent {
                    kind: KeyEventKind::Release,
                    ..
                })
            ) {
                // ConPTY may interleave release records with the pressed
                // characters generated by one paste write. They carry no TUI
                // action and must not split the candidate batch.
                index += 1;
            } else {
                break;
            }
        }

        let char_count = text.chars().count();
        if (has_newline && char_count > 1) || char_count >= WINDOWS_CONSOLE_PASTE_MIN_CHARS {
            output.push(CEvent::Paste(text));
        } else {
            output.extend(events[start..content_end].iter().cloned());
        }
        if let Some(enter) = trailing_submit {
            output.push(enter);
        }
    }
    output
}

#[cfg(windows)]
const WINDOWS_CONSOLE_PASTE_BURST_START_INTERVAL: Duration = Duration::from_millis(8);
#[cfg(windows)]
const WINDOWS_CONSOLE_PASTE_BURST_IDLE_INTERVAL: Duration = Duration::from_millis(150);

struct ObservedTerminalEvent {
    event: CEvent,
    observed_at: Instant,
}

enum TerminalSourceEvent {
    Event(ObservedTerminalEvent),
    Error(String),
}

#[cfg(windows)]
fn coalesce_observed_windows_console_events(events: Vec<ObservedTerminalEvent>) -> Vec<CEvent> {
    coalesce_windows_console_paste_events(
        events.into_iter().map(|observed| observed.event).collect(),
    )
}

#[cfg(any(windows, test))]
fn windows_console_paste_burst_started(events: &[TerminalSourceEvent]) -> bool {
    let candidates = events
        .iter()
        .filter_map(|event| {
            let TerminalSourceEvent::Event(observed) = event else {
                return None;
            };
            windows_console_paste_char(&observed.event).map(|ch| (&observed.event, ch))
        })
        .collect::<Vec<_>>();
    if candidates.len() >= WINDOWS_CONSOLE_PASTE_MIN_CHARS {
        return true;
    }

    candidates.iter().enumerate().any(|(index, (event, ch))| {
        if *ch != '\n' || index + 1 >= candidates.len() {
            return false;
        }
        // A final plain Enter is a submit key after an IME commit. A newline
        // followed by another character (including ConPTY's Ctrl+Enter half
        // of CRLF) is unambiguously content from a multiline paste.
        matches!(
            event,
            CEvent::Key(KeyEvent {
                code: KeyCode::Enter | KeyCode::Char('\n' | '\r'),
                ..
            })
        )
    })
}

impl TerminalProbeResponseFilter {
    fn new(now: Instant) -> Self {
        Self {
            active: true,
            expires_at: now + TERMINAL_PROBE_RESPONSE_FILTER_WINDOW,
            pending_events: Vec::new(),
            pending_text: String::new(),
            discarded_responses: 0,
        }
    }

    fn process(&mut self, event: CEvent, now: Instant) -> Vec<CEvent> {
        if !self.active || (self.pending_events.is_empty() && now > self.expires_at) {
            self.active = false;
            return vec![event];
        }

        let Some(ch) = terminal_probe_response_char(&event) else {
            let mut events = self.flush_pending();
            if matches!(event, CEvent::Paste(_)) {
                self.active = false;
            }
            events.push(event);
            return events;
        };

        if !terminal_probe_response_candidate_char(ch) {
            let mut events = self.flush_pending();
            self.active = false;
            events.push(event);
            return events;
        }

        self.pending_text.push(ch);
        self.pending_events.push(event);

        if terminal_probe_response_complete(&self.pending_text) {
            self.pending_text.clear();
            self.pending_events.clear();
            self.discarded_responses = self.discarded_responses.saturating_add(1);
            if self.discarded_responses >= 2 {
                self.active = false;
            }
            return Vec::new();
        }

        if self.pending_text.len() <= TERMINAL_PROBE_RESPONSE_MAX_CHARS
            && terminal_probe_response_prefix(&self.pending_text)
        {
            return Vec::new();
        }

        self.active = false;
        self.flush_pending()
    }

    fn flush_pending(&mut self) -> Vec<CEvent> {
        self.pending_text.clear();
        std::mem::take(&mut self.pending_events)
    }
}

fn terminal_probe_response_char(event: &CEvent) -> Option<char> {
    let CEvent::Key(key) = event else {
        return None;
    };
    if !matches!(key.kind, KeyEventKind::Press | KeyEventKind::Repeat) {
        return None;
    }
    if !key.modifiers.is_empty() {
        return None;
    }
    match key.code {
        KeyCode::Char(ch) if ch.is_ascii() && !ch.is_ascii_control() => Some(ch),
        _ => None,
    }
}

fn terminal_probe_response_candidate_char(ch: char) -> bool {
    ch.is_ascii_hexdigit() || matches!(ch, ';' | ':' | '/' | 'r' | 'g' | 'b' | 'a')
}

fn terminal_probe_response_complete(text: &str) -> bool {
    consume_terminal_probe_color(text, "10").is_some_and(|end| end == text.len())
        || consume_terminal_probe_color(text, "11").is_some_and(|end| end == text.len())
}

fn terminal_probe_response_prefix(text: &str) -> bool {
    terminal_probe_color_prefix(text, "10") || terminal_probe_color_prefix(text, "11")
}

fn terminal_probe_color_prefix(text: &str, slot: &str) -> bool {
    let rgb_prefix = format!("{slot};rgb:");
    let rgba_prefix = format!("{slot};rgba:");
    if rgb_prefix.starts_with(text) || rgba_prefix.starts_with(text) {
        return true;
    }
    let Some(rest) = text
        .strip_prefix(&rgb_prefix)
        .or_else(|| text.strip_prefix(&rgba_prefix))
    else {
        return false;
    };
    terminal_probe_color_payload_prefix(rest)
}

fn terminal_probe_color_payload_prefix(payload: &str) -> bool {
    if payload.is_empty() {
        return true;
    }
    let mut component_count = 0usize;
    for component in payload.split('/') {
        component_count += 1;
        if component_count > 4 {
            return false;
        }
        if component.len() > 4 || !component.chars().all(|ch| ch.is_ascii_hexdigit()) {
            return false;
        }
    }
    true
}

fn consume_terminal_probe_color(text: &str, slot: &str) -> Option<usize> {
    let (prefix_len, component_count) = if text.starts_with(&format!("{slot};rgba:")) {
        (slot.len() + ";rgba:".len(), 4)
    } else if text.starts_with(&format!("{slot};rgb:")) {
        (slot.len() + ";rgb:".len(), 3)
    } else {
        return None;
    };
    let payload = &text[prefix_len..];
    let mut parts = payload.split('/');
    for _ in 0..component_count {
        let component = parts.next()?;
        if component.len() != 4 || !component.chars().all(|ch| ch.is_ascii_hexdigit()) {
            return None;
        }
    }
    if parts.next().is_some() {
        return None;
    }
    Some(text.len())
}

#[derive(Clone)]
pub(super) struct TerminalEventController {
    tx: mpsc::UnboundedSender<TerminalEventCommand>,
}

impl TerminalEventController {
    pub(super) async fn pause(&self) {
        let (ack_tx, ack_rx) = oneshot::channel();
        if self.tx.send(TerminalEventCommand::Pause(ack_tx)).is_err() {
            return;
        }
        if tokio::time::timeout(Duration::from_millis(250), ack_rx)
            .await
            .is_err()
        {
            warn!("timed out waiting for terminal event reader to pause");
        }
    }

    pub(super) fn resume(&self) {
        let _ = self.tx.send(TerminalEventCommand::Resume);
    }
}

pub(super) fn spawn_terminal_event_reader(tx: AppEventSender) -> TerminalEventController {
    let (control_tx, mut control_rx) = mpsc::unbounded_channel::<TerminalEventCommand>();
    let (source_tx, mut source_rx) = mpsc::unbounded_channel::<TerminalSourceEvent>();
    tokio::spawn(async move {
        let mut paused = false;
        let trace_started_at = Instant::now();
        let mut input_trace = std::env::var_os("KCODER_TUI_INPUT_TRACE")
            .and_then(|path| std::fs::File::create(path).ok())
            .map(BufWriter::new);
        loop {
            if paused {
                match control_rx.recv().await {
                    Some(TerminalEventCommand::Pause(ack_tx)) => {
                        let _ = ack_tx.send(());
                    }
                    Some(TerminalEventCommand::Resume) => {
                        paused = false;
                    }
                    None => break,
                }
                continue;
            }

            let mut events = event::EventStream::new();
            loop {
                tokio::select! {
                    command = control_rx.recv() => {
                        match command {
                            Some(TerminalEventCommand::Pause(ack_tx)) => {
                                drop(events);
                                paused = true;
                                let _ = ack_tx.send(());
                                break;
                            }
                            Some(TerminalEventCommand::Resume) => {}
                            None => return,
                        }
                    }
                    event = events.next() => {
                        match event {
                            Some(Ok(ev)) => {
                                if let Some(trace) = input_trace.as_mut() {
                                    let _ = writeln!(
                                        trace,
                                        "{}\t{:?}",
                                        Instant::now()
                                            .saturating_duration_since(trace_started_at)
                                            .as_micros(),
                                        ev
                                    );
                                }
                                if source_tx
                                    .send(TerminalSourceEvent::Event(ObservedTerminalEvent {
                                        event: ev,
                                        observed_at: Instant::now(),
                                    }))
                                    .is_err()
                                {
                                    return;
                                }
                            }
                            Some(Err(e)) => {
                                warn!("terminal event stream error: {}", e);
                                let _ = source_tx.send(TerminalSourceEvent::Error(e.to_string()));
                                return;
                            }
                            None => return,
                        }
                    }
                }
            }
        }
    });

    tokio::spawn(async move {
        let mut probe_response_filter = TerminalProbeResponseFilter::new(Instant::now());
        while let Some(first) = source_rx.recv().await {
            #[cfg(not(windows))]
            let source_events = vec![first];
            #[cfg(windows)]
            let mut source_events = vec![first];
            #[cfg(windows)]
            if matches!(
                source_events.first(),
                Some(TerminalSourceEvent::Event(observed))
                    if windows_console_paste_char(&observed.event).is_some()
            ) {
                tokio::time::sleep(
                    WINDOWS_CONSOLE_PASTE_BURST_START_INTERVAL + Duration::from_millis(1),
                )
                .await;
                while source_events.len() < 4096 {
                    match source_rx.try_recv() {
                        Ok(event) => source_events.push(event),
                        Err(_) => break,
                    }
                }
                // ConPTY emits a single bracketed-paste write as ordinary
                // console key records. Retain only an unambiguous long or
                // multiline paste across the occasional 40-120ms scheduler
                // stalls observed on Windows Server. Short typing and IME
                // commits are forwarded after the initial 9ms window.
                if windows_console_paste_burst_started(&source_events) {
                    while source_events.len() < 4096 {
                        match tokio::time::timeout(
                            WINDOWS_CONSOLE_PASTE_BURST_IDLE_INTERVAL,
                            source_rx.recv(),
                        )
                        .await
                        {
                            Ok(Some(event)) => source_events.push(event),
                            Ok(None) | Err(_) => break,
                        }
                    }
                }
            }

            let mut filtered_events = Vec::with_capacity(source_events.len());
            for source_event in source_events {
                let observed = match source_event {
                    TerminalSourceEvent::Event(observed) => observed,
                    TerminalSourceEvent::Error(error) => {
                        let _ = tx
                            .send_ordered(AppEvent::Fatal(format!(
                                "terminal event stream failed: {error}"
                            )))
                            .await;
                        return;
                    }
                };
                filtered_events.extend(
                    probe_response_filter
                        .process(observed.event, observed.observed_at)
                        .into_iter()
                        .map(|event| ObservedTerminalEvent {
                            event,
                            observed_at: observed.observed_at,
                        }),
                );
            }
            #[cfg(windows)]
            let filtered_events = coalesce_observed_windows_console_events(filtered_events);
            #[cfg(not(windows))]
            let filtered_events = filtered_events
                .into_iter()
                .map(|observed| observed.event)
                .collect::<Vec<_>>();
            for event in filtered_events {
                if !tx.send_ordered(AppEvent::Terminal(event)).await {
                    return;
                }
            }
        }
    });

    TerminalEventController { tx: control_tx }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key_char_event(ch: char) -> CEvent {
        CEvent::Key(KeyEvent::new(KeyCode::Char(ch), KeyModifiers::NONE))
    }

    fn events_to_chars(events: &[CEvent]) -> String {
        events
            .iter()
            .filter_map(|event| match event {
                CEvent::Key(key) => match key.code {
                    KeyCode::Char(ch) => Some(ch),
                    _ => None,
                },
                _ => None,
            })
            .collect()
    }

    #[test]
    fn terminal_probe_response_filter_discards_late_osc_color_reply_chars() {
        let now = Instant::now();
        let mut filter = TerminalProbeResponseFilter::new(now);
        let mut emitted = Vec::new();

        for ch in "10;rgb:dbdb/e7e7/efef11;rgb:1010/1313/1616".chars() {
            emitted.extend(filter.process(key_char_event(ch), now));
        }

        assert!(emitted.is_empty());
        emitted.extend(filter.process(key_char_event('x'), now));
        assert_eq!(events_to_chars(&emitted), "x");
    }

    #[test]
    fn terminal_probe_response_filter_handles_a_delayed_terminal_attachment() {
        let now = Instant::now();
        let delayed = now + Duration::from_secs(30);
        let mut filter = TerminalProbeResponseFilter::new(now);
        let mut emitted = Vec::new();

        for ch in "10;rgb:dbdb/e7e7/efef11;rgb:1010/1313/1616".chars() {
            emitted.extend(filter.process(key_char_event(ch), delayed));
        }

        assert!(emitted.is_empty());
        emitted.extend(filter.process(key_char_event('x'), delayed));
        assert_eq!(events_to_chars(&emitted), "x");
    }

    #[test]
    fn terminal_probe_response_filter_survives_osc_framing_key_events() {
        let now = Instant::now();
        let mut filter = TerminalProbeResponseFilter::new(now);
        let mut emitted = filter.process(
            CEvent::Key(KeyEvent::new(KeyCode::Esc, KeyModifiers::NONE)),
            now,
        );
        for ch in "10;rgb:dbdb/e7e7/efef11;rgb:1010/1313/1616".chars() {
            emitted.extend(filter.process(key_char_event(ch), now));
        }

        assert_eq!(emitted.len(), 1, "only the framing Esc should pass through");
        assert!(matches!(emitted[0], CEvent::Key(key) if key.code == KeyCode::Esc));
    }

    #[test]
    fn terminal_probe_response_filter_stops_after_real_user_input() {
        let now = Instant::now();
        let mut filter = TerminalProbeResponseFilter::new(now);
        let mut emitted = filter.process(key_char_event('x'), now);
        for ch in "10;rgb:dbdb/e7e7/efef".chars() {
            emitted.extend(filter.process(key_char_event(ch), now));
        }

        assert_eq!(events_to_chars(&emitted), "x10;rgb:dbdb/e7e7/efef");
    }

    #[test]
    fn terminal_probe_response_filter_releases_normal_input_in_order() {
        let now = Instant::now();
        let mut filter = TerminalProbeResponseFilter::new(now);
        let mut emitted = Vec::new();

        for ch in "12tell".chars() {
            emitted.extend(filter.process(key_char_event(ch), now));
        }

        assert_eq!(events_to_chars(&emitted), "12tell");
    }

    #[test]
    fn windows_console_multiline_key_batch_becomes_one_paste_event() {
        let events = vec![
            key_char_event('a'),
            key_char_event('b'),
            CEvent::Key(KeyEvent::new(KeyCode::Enter, KeyModifiers::NONE)),
            key_char_event('\u{6606}'),
            key_char_event('\u{4ed1}'),
        ];

        let coalesced = coalesce_windows_console_paste_events(events);

        assert_eq!(
            coalesced,
            vec![CEvent::Paste("ab\n\u{6606}\u{4ed1}".to_string())]
        );
    }

    #[test]
    fn windows_console_conpty_crlf_pair_becomes_one_paste_newline() {
        let events = vec![
            key_char_event('a'),
            CEvent::Key(KeyEvent::new(KeyCode::Enter, KeyModifiers::NONE)),
            CEvent::Key(KeyEvent::new(KeyCode::Enter, KeyModifiers::CONTROL)),
            key_char_event('\u{6606}'),
            key_char_event('\u{4ed1}'),
        ];

        let coalesced = coalesce_windows_console_paste_events(events);

        assert_eq!(
            coalesced,
            vec![CEvent::Paste("a\n\u{6606}\u{4ed1}".to_string())]
        );
    }

    #[test]
    fn windows_console_long_key_batch_keeps_first_character_in_paste() {
        let text = format!("p{}", "x".repeat(WINDOWS_CONSOLE_PASTE_MIN_CHARS));
        let events = text.chars().map(key_char_event).collect();

        let coalesced = coalesce_windows_console_paste_events(events);

        assert_eq!(coalesced, vec![CEvent::Paste(text)]);
    }

    #[test]
    fn windows_console_short_typed_batch_stays_as_key_events() {
        let events = "abc".chars().map(key_char_event).collect::<Vec<_>>();

        let coalesced = coalesce_windows_console_paste_events(events.clone());

        assert_eq!(coalesced, events);
    }

    #[test]
    fn windows_console_ime_commit_keeps_trailing_enter_as_submit_key() {
        let text = "输入法提交";
        let mut events = text.chars().map(key_char_event).collect::<Vec<_>>();
        let enter = CEvent::Key(KeyEvent::new(KeyCode::Enter, KeyModifiers::NONE));
        events.push(enter.clone());

        let coalesced = coalesce_windows_console_paste_events(events);

        assert_eq!(coalesced.last(), Some(&enter));
        assert!(
            coalesced[..coalesced.len() - 1]
                .iter()
                .all(|event| { !matches!(event, CEvent::Paste(pasted) if pasted.contains('\n')) })
        );
    }

    #[test]
    fn windows_console_extended_wait_requires_an_unambiguous_paste_shape() {
        let started = Instant::now();
        let single = vec![TerminalSourceEvent::Event(ObservedTerminalEvent {
            event: key_char_event('a'),
            observed_at: started,
        })];
        assert!(!windows_console_paste_burst_started(&single));

        let ime_commit = vec![
            TerminalSourceEvent::Event(ObservedTerminalEvent {
                event: key_char_event('a'),
                observed_at: started,
            }),
            TerminalSourceEvent::Event(ObservedTerminalEvent {
                event: key_char_event('b'),
                observed_at: started + Duration::from_millis(1),
            }),
            TerminalSourceEvent::Event(ObservedTerminalEvent {
                event: CEvent::Key(KeyEvent::new(KeyCode::Enter, KeyModifiers::NONE)),
                observed_at: started + Duration::from_millis(120),
            }),
        ];
        assert!(!windows_console_paste_burst_started(&ime_commit));

        let multiline_paste = vec![
            TerminalSourceEvent::Event(ObservedTerminalEvent {
                event: key_char_event('a'),
                observed_at: started,
            }),
            TerminalSourceEvent::Event(ObservedTerminalEvent {
                event: CEvent::Key(KeyEvent::new(KeyCode::Enter, KeyModifiers::NONE)),
                observed_at: started + Duration::from_millis(1),
            }),
            TerminalSourceEvent::Event(ObservedTerminalEvent {
                event: key_char_event('b'),
                observed_at: started + Duration::from_millis(2),
            }),
        ];
        assert!(windows_console_paste_burst_started(&multiline_paste));
    }
}
