use kcoder_tools::cron::{
    APP_PROJECT_CRON_OWNER, CronFire, CronScheduler, SessionCronSubscription,
};
use serde_json::{Value, json};
use std::collections::{BTreeMap, VecDeque};
use std::sync::Arc;

/// Observes only requests generated by this connection, never client-supplied ID prefixes.
#[derive(Clone)]
pub(super) struct AutomationResponses {
    scheduler: Arc<CronScheduler>,
    pending: Arc<std::sync::Mutex<BTreeMap<String, &'static str>>>,
}

impl AutomationResponses {
    pub(super) fn new(scheduler: Arc<CronScheduler>) -> Self {
        Self {
            scheduler,
            pending: Arc::default(),
        }
    }

    pub(super) fn register(&self, request: &Value) {
        let stage = match request["method"].as_str() {
            Some("thread/start") => "creating_thread",
            Some("turn/start") => "starting_turn",
            _ => return,
        };
        if let Some(id) = request["id"].as_str() {
            self.pending
                .lock()
                .unwrap_or_else(|p| p.into_inner())
                .insert(id.into(), stage);
        }
    }

    pub(super) fn observe(&self, response: &Value) {
        if response.get("result").is_none() && response.get("error").is_none() {
            return;
        }
        if let Some(id) = response["id"].as_str() {
            self.finish(
                id,
                response.get("error").map(|error| {
                    error["message"]
                        .as_str()
                        .unwrap_or("Automation request failed")
                }),
            );
        }
    }

    pub(super) fn dispatch_failed(&self, id: &Value, error: &str) {
        if let Some(id) = id.as_str() {
            self.finish(id, Some(error));
        }
    }

    fn finish(&self, id: &str, error: Option<&str>) {
        let stage = self
            .pending
            .lock()
            .unwrap_or_else(|p| p.into_inner())
            .remove(id);
        if let (Some(stage), Some(error)) = (stage, error)
            && let Err(persist_error) = self.scheduler.execution_request_failed(id, stage, error)
        {
            tracing::warn!(%persist_error, request_id = id, "automation admission failure could not be persisted; no replay");
        }
    }
}

pub(super) struct ProjectAutomations {
    scheduler: Arc<CronScheduler>,
    enabled: bool,
    workspace_path: String,
    warned: bool,
    subscription: Option<SessionCronSubscription>,
    pending: BTreeMap<String, CronFire>,
    requests: VecDeque<(Value, Option<CronFire>)>,
    last_counts: Option<(usize, usize)>,
}

impl ProjectAutomations {
    /// Final shutdown step: unsubscribe while schedule writes and firing remain fenced.
    pub(super) fn stop_if_idle(&mut self) -> bool {
        let Ok(Some(_reservation)) = self.scheduler.try_reserve_idle() else {
            return false;
        };
        if !self.pending.is_empty()
            || !self.requests.is_empty()
            || self
                .subscription
                .as_ref()
                .is_some_and(SessionCronSubscription::has_pending_events)
        {
            return false;
        }
        self.subscription.take();
        self.enabled = false;
        true
    }
    pub(super) fn resource_activity(&self) -> (Option<usize>, usize, bool) {
        (
            self.last_counts.map(|counts| counts.0),
            self.pending.len() + self.requests.len(),
            self.subscription.is_some(),
        )
    }
    pub(super) fn new(
        scheduler: Arc<CronScheduler>,
        enabled: bool,
        workspace_path: String,
    ) -> Self {
        Self {
            scheduler,
            enabled,
            workspace_path,
            warned: false,
            subscription: None,
            pending: BTreeMap::new(),
            requests: VecDeque::new(),
            last_counts: None,
        }
    }

    pub(super) fn activate(&mut self) {
        if !self.enabled || self.subscription.is_some() {
            return;
        }
        match self.scheduler.migrate_app_jobs_to_project() {
            Ok(_) => {
                self.subscription = Some(
                    self.scheduler
                        .subscribe_session(APP_PROJECT_CRON_OWNER.to_string()),
                )
            }
            Err(error) if !self.warned => {
                self.warned = true;
                tracing::warn!(%error, "project automation migration is not ready");
            }
            Err(_) => {}
        }
    }

    pub(super) async fn receive(&mut self) {
        match self.subscription.as_mut() {
            Some(subscription) => {
                if let Ok(fire) = subscription.recv().await {
                    if let Some(retained) = self.pending.get_mut(&fire.id) {
                        match self.scheduler.coalesce_execution(retained, &fire) {
                            Ok(()) => {
                                retained.coalesced = retained
                                    .coalesced
                                    .saturating_add(fire.coalesced)
                                    .saturating_add(1)
                            }
                            Err(error) => {
                                tracing::warn!(%error, trigger_id = %fire.trigger_id(), "automation merge persistence failed; trigger will not replay")
                            }
                        }
                    } else {
                        self.pending.insert(fire.id.clone(), fire);
                    }
                }
            }
            None => std::future::pending().await,
        }
    }

    pub(super) fn queue_if_idle(&mut self, idle: bool) {
        if idle
            && self.requests.is_empty()
            && let Some((_, fire)) = self.pending.pop_first()
        {
            match self
                .scheduler
                .begin_execution(&fire, std::path::Path::new(&self.workspace_path))
            {
                Ok(true) => self.requests.push_back((
                    json!({
                        "id":fire.execution_thread_request_id(), "method":"thread/start",
                        "params":{"clientRequestId":fire.execution_thread_request_id()}
                    }),
                    Some(fire),
                )),
                Ok(false) => {
                    tracing::warn!(trigger_id = %fire.trigger_id(), "automation already claimed; will not replay")
                }
                Err(error) => {
                    tracing::warn!(%error, trigger_id = %fire.trigger_id(), "automation claim uncertain; will not replay")
                }
            }
        }
    }

    pub(super) fn next_request(&mut self) -> Option<(Value, Option<CronFire>)> {
        self.requests.pop_front()
    }

    pub(super) fn take_state_change(&mut self) -> Option<Value> {
        self.subscription.as_ref()?;
        let job_count = self
            .scheduler
            .list_for_session(APP_PROJECT_CRON_OWNER)
            .ok()?
            .len();
        let pending_count = self.pending.len() + self.requests.len();
        if self.last_counts == Some((job_count, pending_count)) {
            return None;
        }
        self.last_counts = Some((job_count, pending_count));
        Some(json!(kcoder_app_protocol::AutomationStateChangedParams {
            job_count,
            pending_count
        }))
    }

    pub(super) fn start_turn(
        &mut self,
        fire: &CronFire,
        thread_id: &str,
    ) -> Result<String, String> {
        let prompt = format!(
            "[scheduled task {} due at {}] {}\nAdditional missed triggers coalesced: {}.",
            fire.id, fire.scheduled_at, fire.prompt, fire.coalesced
        );
        let request_id = fire.execution_turn_request_id();
        self.scheduler
            .execution_thread_created(fire, thread_id, &request_id)?;
        self.requests.push_front((json!({"id":request_id,"method":"turn/start","params":{"threadId":thread_id,"clientMessageId":request_id,"input":[{"type":"text","text":prompt}]}}), None));
        Ok(request_id)
    }

    /// Called after dispatch for all generated requests, including admission rejection.
    pub(super) fn request_failed(&self, request_id: &str, stage: &str, error: &str) {
        if let Err(persist_error) = self
            .scheduler
            .execution_request_failed(request_id, stage, error)
        {
            tracing::warn!(%persist_error, request_id, "automation startup outcome is uncertain; no replay");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    async fn response_fixture() -> (tempfile::TempDir, Arc<CronScheduler>, CronFire) {
        let root = tempfile::tempdir().unwrap();
        let scheduler = Arc::new(CronScheduler::load(root.path()));
        let job = scheduler
            .create_for_session(
                APP_PROJECT_CRON_OWNER.into(),
                "admission fixture".into(),
                kcoder_tools::cron::CronSchedule::At {
                    at: (Utc::now() + chrono::Duration::seconds(60)).to_rfc3339(),
                },
                Some(0),
            )
            .unwrap();
        let mut subscription = scheduler.subscribe_session(APP_PROJECT_CRON_OWNER.into());
        let path = root.path().join(".kcoder/cron/jobs.json");
        let mut fixture: Value = serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
        fixture["jobs"][0]["next_run_at"] = json!(Utc::now() - chrono::Duration::seconds(1));
        std::fs::write(&path, serde_json::to_vec(&fixture).unwrap()).unwrap();
        scheduler.schedule_runner();
        let fire = tokio::time::timeout(std::time::Duration::from_secs(3), subscription.recv())
            .await
            .unwrap()
            .unwrap();
        assert_eq!(fire.id, job.id);
        assert!(scheduler.begin_execution(&fire, root.path()).unwrap());
        (root, scheduler, fire)
    }

    #[tokio::test]
    async fn generated_admission_error_is_recorded_and_unregistered_prefix_is_ignored() {
        let (_root, scheduler, fire) = response_fixture().await;
        let observer = AutomationResponses::new(scheduler.clone());
        let id = fire.execution_thread_request_id();
        let error = json!({"id": id, "error": {"message": "thread capacity reached"}});
        observer.observe(&error);
        assert_eq!(
            scheduler
                .execution_diagnostics(Some(APP_PROJECT_CRON_OWNER))
                .unwrap()["runs"][0]["status"],
            "creating_thread"
        );
        observer.register(&json!({"id": id, "method": "thread/start"}));
        observer.observe(&json!({"id": id, "method": "notification"}));
        observer.observe(&error);
        let run = &scheduler
            .execution_diagnostics(Some(APP_PROJECT_CRON_OWNER))
            .unwrap()["runs"][0];
        assert_eq!(run["status"], "failed");
        assert_eq!(run["failureStage"], "creating_thread");
        assert_eq!(run["error"], "thread capacity reached");
        assert_eq!(run["automaticReplay"], false);
        observer.observe(&json!({"id": id, "result": {"thread": {"id": "phantom"}}}));
        assert_eq!(
            scheduler
                .execution_diagnostics(Some(APP_PROJECT_CRON_OWNER))
                .unwrap()["runs"][0]["status"],
            "failed"
        );
    }

    #[tokio::test]
    async fn generated_turn_dispatch_error_records_failure_after_thread_creation() {
        let (_root, scheduler, fire) = response_fixture().await;
        let id = fire.execution_turn_request_id();
        scheduler
            .execution_thread_created(&fire, "actual-thread", &id)
            .unwrap();
        let observer = AutomationResponses::new(scheduler.clone());
        observer.register(&json!({"id": id, "method": "turn/start"}));
        observer.dispatch_failed(&json!(id), "connection dispatch failed");
        let run = &scheduler
            .execution_diagnostics(Some(APP_PROJECT_CRON_OWNER))
            .unwrap()["runs"][0];
        assert_eq!(run["status"], "failed");
        assert_eq!(run["threadId"], "actual-thread");
        assert_eq!(run["failureStage"], "starting_turn");
    }

    #[test]
    fn state_notifications_are_changed_only_and_disabled_profiles_do_not_subscribe() {
        let root = tempfile::tempdir().unwrap();
        let scheduler = Arc::new(CronScheduler::load(root.path()));
        let mut disabled = ProjectAutomations::new(
            Arc::clone(&scheduler),
            false,
            root.path().to_string_lossy().into_owned(),
        );
        disabled.activate();
        assert!(disabled.take_state_change().is_none());
        assert_eq!(disabled.resource_activity(), (None, 0, false));
        let mut enabled =
            ProjectAutomations::new(scheduler, true, root.path().to_string_lossy().into_owned());
        enabled.activate();
        assert_eq!(
            enabled.take_state_change().unwrap(),
            json!({"jobCount":0,"pendingCount":0})
        );
        assert!(enabled.take_state_change().is_none());
        assert_eq!(enabled.resource_activity(), (Some(0), 0, true));
        assert!(enabled.stop_if_idle());
        enabled.activate();
        assert!(!enabled.resource_activity().2);
    }

    #[tokio::test]
    async fn due_work_waits_for_idle_and_starts_a_new_thread_before_its_turn() {
        let root = tempfile::tempdir().unwrap();
        let mut automation = ProjectAutomations::new(
            Arc::new(CronScheduler::load(root.path())),
            true,
            root.path().to_string_lossy().into_owned(),
        );
        automation.activate();
        let job = automation
            .scheduler
            .create_for_session(
                APP_PROJECT_CRON_OWNER.into(),
                "standalone task".into(),
                kcoder_tools::cron::CronSchedule::At {
                    at: (Utc::now() + chrono::Duration::seconds(60)).to_rfc3339(),
                },
                Some(0),
            )
            .unwrap();
        let path = root.path().join(".kcoder/cron/jobs.json");
        let mut fixture: Value = serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
        fixture["jobs"][0]["next_run_at"] = json!(Utc::now() - chrono::Duration::seconds(1));
        std::fs::write(&path, serde_json::to_vec(&fixture).unwrap()).unwrap();
        automation.scheduler.schedule_runner();
        tokio::time::timeout(std::time::Duration::from_secs(3), automation.receive())
            .await
            .unwrap();
        assert!(automation.pending.contains_key(&job.id));
        assert_eq!(automation.resource_activity(), (None, 1, true));
        assert!(!automation.stop_if_idle());
        automation.queue_if_idle(false);
        assert!(automation.next_request().is_none());
        automation.queue_if_idle(true);
        assert_eq!(automation.resource_activity().1, 1);
        let (start, fire) = automation.next_request().unwrap();
        assert_eq!(start["method"], "thread/start");
        assert!(start["params"].get("threadId").is_none());
        let request_id = automation
            .start_turn(&fire.unwrap(), "fresh-thread")
            .unwrap();
        let (turn, _) = automation.next_request().unwrap();
        assert_eq!(turn["method"], "turn/start");
        assert_eq!(turn["id"], request_id);
        assert!(request_id.starts_with("kcoder-automation-turn:"));
        assert_eq!(turn["params"]["clientMessageId"], request_id);
        assert!(turn["params"].get("retryOperationId").is_none());
        assert_eq!(turn["params"]["threadId"], "fresh-thread");
        assert!(
            turn["params"]["input"][0]["text"]
                .as_str()
                .unwrap()
                .contains("standalone task")
        );
    }
}
